name: Java tests and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Set postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: SICOP
        postgresql password: 728040

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Test
      run: ./gradlew test
      
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql db: SICOP
        postgresql password: 728040

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run build with gradle
      run: ./gradlew clean build

  publish:
    needs: [build]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
