stages: # Etapas do pipeline
  - build
  - test
  - deploy

build: # Job 1
  stage: build
  # Imagem docker do jdk8 que será usada para executar o build em um container
  image: adoptopenjdk/openjdk8
  script:
    - ./gradlew assemble # Comando gradle que realiza o build do projeto
  artifacts:
    paths:
      - build/libs/*.jar # Pasta no repositório onde será salvo o build

test: # Job 2
  stage: test
  image: adoptopenjdk/openjdk8
  script:
    - ./gradlew check # Comando gradle que executa os testes do projeto

deploy_prod: # Job 3
  stage: deploy
  image: ruby:latest
  script:
    #- apt-get update -qy # Instalação do ruby pra utilizar a ferramenta dpl
    #- apt-get install -y ruby-dev
    - gem install dpl # Ferramenta de implantação desenvolvida pelo Travis CI
    # Para implantar, a dpl precisa saber quem será:
    #   provider: onde será implantada a aplicação
    #   app: nome da aplicação no provider
    #   api-key: no caso do Heroku, a chave de acesso para a conta
    - dpl --provider=heroku --app=sicop --api-key=$HEROKU_API_KEY
  only:
    - master


